//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 06:50:20 AM PST 
//


package restAddressService.client;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candidate"
})
@XmlRootElement(name = "candidates")
public class Candidates {

    @XmlElement(required = true)
    protected List<Candidates.Candidate> candidate;

   
    public List<Candidates.Candidate> getCandidate() {
        if (candidate == null) {
            candidate = new ArrayList<Candidates.Candidate>();
        }
        return this.candidate;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inputIndex",
        "candidateIndex",
        "addressee",
        "deliveryLine1",
        "deliveryLine2",
        "lastLine",
        "deliveryPointBarcode",
        "components",
        "metadata",
        "analysis"
    })
    public static class Candidate {

        @XmlElement(name = "input_index")
        @XmlSchemaType(name = "unsignedInt")
        protected long inputIndex;
        @XmlElement(name = "candidate_index")
        @XmlSchemaType(name = "unsignedInt")
        protected long candidateIndex;
        protected String addressee;
        @XmlElement(name = "delivery_line_1")
        protected String deliveryLine1;
        @XmlElement(name = "delivery_line_2")
        protected String deliveryLine2;
        @XmlElement(name = "last_line")
        protected String lastLine;
        @XmlElement(name = "delivery_point_barcode")
        protected String deliveryPointBarcode;
        @XmlElement(required = true)
        protected Candidates.Candidate.Components components;
        @XmlElement(required = true)
        protected Candidates.Candidate.Metadata metadata;
        @XmlElement(required = true)
        protected Candidates.Candidate.Analysis analysis;

       
        public long getInputIndex() {
            return inputIndex;
        }

       
        public void setInputIndex(long value) {
            this.inputIndex = value;
        }

        
        public long getCandidateIndex() {
            return candidateIndex;
        }

        /**
         * Sets the value of the candidateIndex property.
         * 
         */
        public void setCandidateIndex(long value) {
            this.candidateIndex = value;
        }

     
        public String getAddressee() {
            if(addressee == null)
                addressee = "";
            return addressee;
        }

       
        public void setAddressee(String value) {
            this.addressee = value;
        }

        
        public String getDeliveryLine1() {
            if(deliveryLine1 == null)
                deliveryLine1 = "";
            return deliveryLine1;
        }

       
        public void setDeliveryLine1(String value) {
            this.deliveryLine1 = value;
        }

       
        public String getDeliveryLine2() {
            if(deliveryLine2 == null)
                deliveryLine2 = "";
            return deliveryLine2;
        }

        
        public void setDeliveryLine2(String value) {
            this.deliveryLine2 = value;
        }

       
        public String getLastLine() {
            if(lastLine == null)
                lastLine = "";
            return lastLine;
        }

        
        public void setLastLine(String value) {
            this.lastLine = value;
        }

       
        public String getDeliveryPointBarcode() {
            if(deliveryPointBarcode == null)
                deliveryPointBarcode = "";
            return deliveryPointBarcode;
        }

        
        public void setDeliveryPointBarcode(String value) {
            this.deliveryPointBarcode = value;
        }

      
        public Candidates.Candidate.Components getComponents() {
            return components;
        }

      
        public void setComponents(Candidates.Candidate.Components value) {
            this.components = value;
        }

      
        public Candidates.Candidate.Metadata getMetadata() {
            return metadata;
        }

        
        public void setMetadata(Candidates.Candidate.Metadata value) {
            this.metadata = value;
        }

       
        public Candidates.Candidate.Analysis getAnalysis() {
            return analysis;
        }

       
        public void setAnalysis(Candidates.Candidate.Analysis value) {
            this.analysis = value;
        }


       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dpvMatchCode",
            "dpvFootnotes",
            "dpvCmra",
            "dpvVacant",
            "active",
            "ewsMatch",
            "footnotes",
            "lacslinkCode",
            "lasclinkIndicator"
        })
        public static class Analysis {

            @XmlElement(name = "dpv_match_code")
            protected String dpvMatchCode;
            @XmlElement(name = "dpv_footnotes")
            protected String dpvFootnotes;
            @XmlElement(name = "dpv_cmra")
            protected String dpvCmra;
            @XmlElement(name = "dpv_vacant")
            protected String dpvVacant;
            protected String active;
            @XmlElement(name = "ews_match")
            protected String ewsMatch;
            protected String footnotes;
            @XmlElement(name = "lacslink_code")
            protected String lacslinkCode;
            @XmlElement(name = "lasclink_indicator")
            protected String lasclinkIndicator;

        
            public String getDpvMatchCode() {
                return dpvMatchCode;
            }

           
            public void setDpvMatchCode(String value) {
                this.dpvMatchCode = value;
            }

            
            public String getDpvFootnotes() {
                return dpvFootnotes;
            }

           
            public void setDpvFootnotes(String value) {
                this.dpvFootnotes = value;
            }

           
            public String getDpvCmra() {
                return dpvCmra;
            }

           
            public void setDpvCmra(String value) {
                this.dpvCmra = value;
            }

           
            public String getDpvVacant() {
                return dpvVacant;
            }

            
            public void setDpvVacant(String value) {
                this.dpvVacant = value;
            }

            
            public String getActive() {
                return active;
            }

            
            public void setActive(String value) {
                this.active = value;
            }

           
            public String getEwsMatch() {
                return ewsMatch;
            }

            
            public void setEwsMatch(String value) {
                this.ewsMatch = value;
            }

            
            public String getFootnotes() {
                if(footnotes == null)
                    footnotes = "";
                return footnotes;
            }

           
            public void setFootnotes(String value) {
                this.footnotes = value;
            }

            
            public String getLacslinkCode() {
                return lacslinkCode;
            }

            
            public void setLacslinkCode(String value) {
                this.lacslinkCode = value;
            }

           
            public String getLasclinkIndicator() {
                return lasclinkIndicator;
            }

            
            public void setLasclinkIndicator(String value) {
                this.lasclinkIndicator = value;
            }

        }//end Analysis

       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urbanization",
            "primaryNumber",
            "streetName",
            "streetPredirection",
            "streetPostdirection",
            "streetSuffix",
            "secondaryNumber",
            "secondaryDesignator",
            "pmbDesignator",
            "pmbNumber",
            "cityName",
            "defaultCityName",
            "stateAbbreviation",
            "zipcode",
            "plus4Code",
            "deliveryPoint",
            "deliveryPointCheckDigit"
        })
        public static class Components {

            protected String urbanization;
            @XmlElement(name = "primary_number")
            protected String primaryNumber;
            @XmlElement(name = "street_name")
            protected String streetName;
            @XmlElement(name = "street_predirection")
            protected String streetPredirection;
            @XmlElement(name = "street_postdirection")
            protected String streetPostdirection;
            @XmlElement(name = "street_suffix")
            protected String streetSuffix;
            @XmlElement(name = "secondary_number")
            protected String secondaryNumber;
            @XmlElement(name = "secondary_designator")
            protected String secondaryDesignator;
            @XmlElement(name = "pmb_designator")
            protected String pmbDesignator;
            @XmlElement(name = "pmb_number")
            protected String pmbNumber;
            @XmlElement(name = "city_name")
            protected String cityName;
            @XmlElement(name = "default_city_name")
            protected String defaultCityName;
            @XmlElement(name = "state_abbreviation")
            protected String stateAbbreviation;
            protected String zipcode;
            @XmlElement(name = "plus4_code")
            protected String plus4Code;
            @XmlElement(name = "delivery_point")
            protected String deliveryPoint;
            @XmlElement(name = "delivery_point_check_digit")
            protected String deliveryPointCheckDigit;

            /**
             * Gets the value of the urbanization property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrbanization() {
                return urbanization;
            }

           
            public void setUrbanization(String value) {
                this.urbanization = value;
            }

            
            public String getPrimaryNumber() {
                if(primaryNumber == null)
                    primaryNumber = "";
                return primaryNumber;
            }

           
            public void setPrimaryNumber(String value) {
                this.primaryNumber = value;
            }

           
            public String getStreetName() {
                if(streetName == null)
                    streetName = "";
                return streetName;
            }

           
            public void setStreetName(String value) {
                this.streetName = value;
            }

          
            public String getStreetPredirection() {
                if(streetPredirection == null)
                    streetPredirection = "";
                return streetPredirection;
            }

            
            public void setStreetPredirection(String value) {
                this.streetPredirection = value;
            }

           
            public String getStreetPostdirection() {
                if(streetPostdirection == null)
                    streetPostdirection = "";
                return streetPostdirection;
            }

           
            public void setStreetPostdirection(String value) {
                this.streetPostdirection = value;
            }

          
            public String getStreetSuffix() {
                if(streetSuffix == null)
                    streetSuffix = "";
                return streetSuffix;
            }

            
            public void setStreetSuffix(String value) {
                this.streetSuffix = value;
            }

          
            public String getSecondaryNumber() {
                if(secondaryNumber == null)
                    secondaryNumber = "";
                return secondaryNumber;
            }

           
            public void setSecondaryNumber(String value) {
                this.secondaryNumber = value;
            }

         
            public String getSecondaryDesignator() {
                if(secondaryDesignator == null)
                    secondaryDesignator = "";
                return secondaryDesignator;
            }

            
            public void setSecondaryDesignator(String value) {
                this.secondaryDesignator = value;
            }

       
            public String getPmbDesignator() {
                if(pmbDesignator == null)
                    pmbDesignator = "";
                return pmbDesignator;
            }

         
            public void setPmbDesignator(String value) {
                this.pmbDesignator = value;
            }

         
            public String getPmbNumber() {
                if(pmbNumber == null)
                    pmbNumber = "";
                return pmbNumber;
            }

       
            public void setPmbNumber(String value) {
                this.pmbNumber = value;
            }

         
            public String getCityName() {
                if(cityName == null)
                    cityName = "";
                return cityName;
            }

         
            public void setCityName(String value) {
                this.cityName = value;
            }

          
            public String getDefaultCityName() {
                if(defaultCityName == null)
                    defaultCityName = "";
                return defaultCityName;
            }

          
            public void setDefaultCityName(String value) {
                this.defaultCityName = value;
            }

            /**
             * Gets the value of the stateAbbreviation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStateAbbreviation() {
                if(stateAbbreviation == null)
                    stateAbbreviation = "";
                return stateAbbreviation;
            }

            /**
             * Sets the value of the stateAbbreviation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStateAbbreviation(String value) {
                this.stateAbbreviation = value;
            }

            /**
             * Gets the value of the zipcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZipcode() {
                if(zipcode == null)
                    zipcode = "";
                return zipcode;
            }

            /**
             * Sets the value of the zipcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZipcode(String value) {
                this.zipcode = value;
            }

            /**
             * Gets the value of the plus4Code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlus4Code() {
                if(plus4Code == null)
                    plus4Code = "";
                return plus4Code;
            }

            /**
             * Sets the value of the plus4Code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlus4Code(String value) {
                this.plus4Code = value;
            }

            /**
             * Gets the value of the deliveryPoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeliveryPoint() {
                return deliveryPoint;
            }

            /**
             * Sets the value of the deliveryPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeliveryPoint(String value) {
                this.deliveryPoint = value;
            }

            /**
             * Gets the value of the deliveryPointCheckDigit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeliveryPointCheckDigit() {
                return deliveryPointCheckDigit;
            }

            /**
             * Sets the value of the deliveryPointCheckDigit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeliveryPointCheckDigit(String value) {
                this.deliveryPointCheckDigit = value;
            }

        } //end Components

      
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "recordType",
            "countyFips",
            "countyName",
            "carrierRoute",
            "congressionalDistrict",
            "buildingDefaultIndicator",
            "rdi",
            "latitude",
            "longitude",
            "precision"
        })
        public static class Metadata {

            @XmlElement(name = "record_type")
            protected String recordType;
            @XmlElement(name = "county_fips")
            protected String countyFips;
            @XmlElement(name = "county_name")
            protected String countyName;
            @XmlElement(name = "carrier_route")
            protected String carrierRoute;
            @XmlElement(name = "congressional_district")
            protected String congressionalDistrict;
            @XmlElement(name = "building_default_indicator")
            protected String buildingDefaultIndicator;
            protected String rdi;
            protected BigDecimal latitude;
            protected BigDecimal longitude;
            protected String precision;

            /**
             * Gets the value of the recordType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordType() {
                return recordType;
            }

            /**
             * Sets the value of the recordType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordType(String value) {
                this.recordType = value;
            }

            /**
             * Gets the value of the countyFips property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountyFips() {
                return countyFips;
            }

            /**
             * Sets the value of the countyFips property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountyFips(String value) {
                this.countyFips = value;
            }

            /**
             * Gets the value of the countyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountyName() {
                return countyName;
            }

            /**
             * Sets the value of the countyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountyName(String value) {
                this.countyName = value;
            }

            /**
             * Gets the value of the carrierRoute property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCarrierRoute() {
                return carrierRoute;
            }

            /**
             * Sets the value of the carrierRoute property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCarrierRoute(String value) {
                this.carrierRoute = value;
            }

            /**
             * Gets the value of the congressionalDistrict property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCongressionalDistrict() {
                return congressionalDistrict;
            }

            /**
             * Sets the value of the congressionalDistrict property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCongressionalDistrict(String value) {
                this.congressionalDistrict = value;
            }

            /**
             * Gets the value of the buildingDefaultIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuildingDefaultIndicator() {
                return buildingDefaultIndicator;
            }

            /**
             * Sets the value of the buildingDefaultIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuildingDefaultIndicator(String value) {
                this.buildingDefaultIndicator = value;
            }

            /**
             * Gets the value of the rdi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRdi() {
                return rdi;
            }

            /**
             * Sets the value of the rdi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRdi(String value) {
                this.rdi = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLatitude(BigDecimal value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLongitude(BigDecimal value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the precision property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrecision() {
                return precision;
            }

            /**
             * Sets the value of the precision property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrecision(String value) {
                this.precision = value;
            }

        }//end MetaData

    } //end Candidate

} //end Candidates
