//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 06:49:31 AM PST 
//


package restAddressService.client;


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;




@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "address"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected List<Request.Address> address;

    
    public List<Request.Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Request.Address>();
        }
        return this.address;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "street",
        "street2",
        "secondary",
        "city",
        "state",
        "zipcode",
        "lastline",
        "addressee",
        "urbanization",
        "candidates",
        "match"
    })
    public static class Address {
       
        
        @XmlElement(required = true)
        protected String street;
        
        
        protected String street2;
        
       
        protected String secondary;
        
        protected String city;
        protected String state;
        protected String zipcode;
        
        
        protected String lastline;
       
        protected String addressee;
       
        protected String urbanization;
        @XmlSchemaType(name = "unsignedByte")
        
        protected Short candidates;
        
        protected String match;

        /**
         * Gets the value of the street property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreet() {
            if(street == null)
                street = "";
            return street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreet(String value) {
            this.street = value;
        }

        /**
         * Gets the value of the street2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreet2() {
            if(street2 == null)
                street2 = "";
            return street2;
        }

        /**
         * Sets the value of the street2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreet2(String value) {
            this.street2 = value;
        }

        /**
         * Gets the value of the secondary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondary() {
            return secondary;
        }

        /**
         * Sets the value of the secondary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondary(String value) {
            this.secondary = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            if(city == null)
                city = "";
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            if(state == null)
                state = "";
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the zipcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipcode() {
            if(zipcode == null)
                zipcode = "";
            return zipcode;
        }

        /**
         * Sets the value of the zipcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipcode(String value) {
            this.zipcode = value;
        }

        /**
         * Gets the value of the lastline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastline() {
            return lastline;
        }

        /**
         * Sets the value of the lastline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastline(String value) {
            this.lastline = value;
        }

        /**
         * Gets the value of the addressee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressee() {
            return addressee;
        }

        /**
         * Sets the value of the addressee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressee(String value) {
            this.addressee = value;
        }

        /**
         * Gets the value of the urbanization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrbanization() {
            return urbanization;
        }

        /**
         * Sets the value of the urbanization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrbanization(String value) {
            this.urbanization = value;
        }

        /**
         * Gets the value of the candidates property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getCandidates() {
            return candidates;
        }

        /**
         * Sets the value of the candidates property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setCandidates(Short value) {
            this.candidates = value;
        }

        public String getMatch() {
            return match;
        }

        public void setMatch(String match) {
            this.match = match;
        }
        
        

    }

}
