package model.customer;
// Generated Jun 8, 2015 7:04:12 PM by Hibernate Tools 4.3.1

//import model.customer.Country;
import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="sakila_2"
)
public class City implements java.io.Serializable {

     private Short cityId;
     private Country countryId;
     private String cityName;
     private Date lastUpdate;
    // private Set<Address> addresses = new HashSet<Address>(0);

    public City() {
    }

    @NotNull(message="Please make a selection.")	
    @Id @GeneratedValue(strategy=IDENTITY)  
    @Column(name="city_id", unique=true, nullable=false)
    public Short getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    @Valid
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Country country) {
        this.countryId = country;
    }
    
    @Column(name="city_name", nullable=false, length=50)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

  /*@OneToMany(fetch=FetchType.LAZY, mappedBy="city_id")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }*/
}


