package model.customer;
// Generated Jun 8, 2015 7:04:12 PM by Hibernate Tools 4.3.1

//import model.customer.Country;
import exception_handler.LoggerResource;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Logger;
//import java.util.HashSet;
//import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="sakila_2"
)
public class City implements java.io.Serializable {

     private Short cityId;
     private Country countryId;
     private String cityName;
     private Date lastUpdate;
    // private Set<Address> addresses = new HashSet<Address>(0);

    public City() {
    }

    @NotNull(message="Please make a selection.")	
    @Id @GeneratedValue(strategy=IDENTITY)  
    @Column(name="city_id", unique=true, nullable=false)
    public Short getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    @Valid
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Country country) {
        this.countryId = country;
    }
    
    @Column(name="city_name", nullable=false, length=50)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    
    

  /*@OneToMany(fetch=FetchType.LAZY, mappedBy="city_id")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }*/

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.cityId);
        hash = 53 * hash + Objects.hashCode(this.countryId);
        hash = 53 * hash + Objects.hashCode(this.cityName);
        hash = 53 * hash + Objects.hashCode(this.lastUpdate);
        return hash;
    }

   /* @Override
    public boolean equals(Object obj) {
        
        String msg = null;
        
        final City other = (City) obj;
        
        Logger logger = LoggerResource.createFileHandler(
                "C:\\Users\\dinah\\myLogs\\Spring7\\is_equal_logger.txt", this.getClass());  
        
        if (this == obj) {
            msg="this == obj";
            logger.info(msg);
            return true;
        }
        if (obj == null) {
             msg="obj == null";
            logger.info(msg);
            return false;
        }
        if (getClass() != obj.getClass()) {
            msg="getClass() != obj.getClass()";
            logger.info(msg);
            return false;
        }
        
        if (!Objects.equals(this.cityName, other.cityName)) {
            msg="!Objects.equals(this.cityName, other.cityName)";
            logger.info(msg);
            return false;
        }
        if (!this.cityId.equals(other.cityId)) {
            msg="!Objects.equals(this.cityId, other.cityId)";
            logger.info(msg);
            return false;
        }
        if (!this.countryId.equals(other.countryId)) {
            msg="!Objects.equals(this.countryId, other.countryId)";
            logger.info(msg);
            return false;
        }
        if (!this.lastUpdate.equals(other.lastUpdate)) {
            msg="!Objects.equals(lastUpdate, other.lastUpdate)";
            logger.info(msg);
            return false;
        }
        
        msg = "City#equals returning true";
        logger.info(msg);
        
        return true;
    } */
}


