package model.customer;
// Generated Jun 8, 2015 7:04:12 PM by Hibernate Tools 4.3.1




import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="sakila_2"
)
public class Country  implements java.io.Serializable {

     
     private Short countryId;
     private String countryName;
     private Date lastUpdate;
    // private Set<City> cities = new HashSet<City>(0);

    public Country() {
    }

    @NotNull
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="country_id", unique=true, nullable=false)
    public Short getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="country_name", nullable=false, length=50)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

  /*  @OneToMany(fetch=FetchType.EAGER, mappedBy="countryId")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    } */
} //end entity


