package model.customer;
// Generated Jul 20, 2015 1:00:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.CascadeType;

/**
 * CustomerOrder generated by hbm2java
 */
@Entity
@Table(name="customer_order"
    ,catalog="sakila_2"
)
public class CustomerOrder  implements java.io.Serializable {


     private Integer orderId;
     private Customer customer;
     private Date orderDate;
     private BigDecimal orderAmount;
     private Set<LineItem> lineItems = new HashSet<LineItem>(0);

    public CustomerOrder() {
    }

	
    public CustomerOrder(Customer customer, Date orderDate, BigDecimal orderAmount) {
        this.customer = customer;
        this.orderDate = orderDate;
        this.orderAmount = orderAmount;
    }
    public CustomerOrder(Customer customer, Date orderDate, BigDecimal orderAmount, Set<LineItem> lineItems) {
       this.customer = customer;
       this.orderDate = orderDate;
       this.orderAmount = orderAmount;
       this.lineItems = lineItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", nullable=false, length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="order_amount", nullable=false, precision=4)
    public BigDecimal getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="customerOrder", cascade=CascadeType.PERSIST)
    public Set<LineItem> getLineItems() {
        return this.lineItems;
    }
    
    public void setLineItems(Set<LineItem> lineItems) {
        this.lineItems = lineItems;
    }

} //end class


