package model.customer;
// Generated Jul 20, 2015 1:00:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import model.Film;

/**
 * LineItem generated by hbm2java
 */
@Entity
@Table(name="line_item"
    ,catalog="sakila_2"
)
public class LineItem  implements java.io.Serializable {


     private Integer id;
     private CustomerOrder customerOrder;
     private Film film;
     private int quantity;

    public LineItem() {
    }

    public LineItem(CustomerOrder customerOrder, Film film) {
       this.customerOrder = customerOrder;
       this.film = film;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }   

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", referencedColumnName="order_id", nullable=false)
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="film_id", nullable=false)
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

}


